export const CONFIG_PAGES = [
  {
    id: "storage",
    title: "MinIO 存储",
    description: "管理本机对象存储、访问端口和数据目录。",
    fields: [
      {
        key: "MINIO_ROOT_USER",
        label: "MinIO 管理员账号",
        help: "登录 MinIO Console 的管理员用户名。",
        defaultValue: "change-me-admin",
        restart: true,
      },
      {
        key: "MINIO_ROOT_PASSWORD",
        label: "MinIO 管理员密码",
        help: "MinIO Console 管理员密码；留空表示保持现有密码。",
        type: "password",
        restart: true,
      },
      {
        key: "MINIO_BUCKET",
        label: "媒体 Bucket",
        help: "Home MinIO 永久保存媒体副本的 Bucket 名称。",
        defaultValue: "waule-media",
        restart: true,
      },
      {
        key: "MINIO_DATA_DIR",
        label: "MinIO 数据目录",
        help: "宿主机保存 MinIO 对象数据的持久化目录。",
        defaultValue: "./data",
        restart: true,
      },
      {
        key: "HOME_MINIO_BIND_ADDRESS",
        label: "监听地址",
        help: "0.0.0.0 允许局域网和 Tailscale 访问；不要在路由器上开放公网端口。",
        defaultValue: "0.0.0.0",
        restart: true,
      },
      {
        key: "MINIO_API_PORT",
        label: "MinIO API 端口",
        help: "NewWaule 和本机工具访问 MinIO S3 API 的宿主机端口。",
        type: "number",
        defaultValue: "19000",
        min: 1,
        max: 65535,
        restart: true,
      },
      {
        key: "MINIO_CONSOLE_PORT",
        label: "MinIO Console 端口",
        help: "浏览器打开 MinIO 官方管理控制台的宿主机端口。",
        type: "number",
        defaultValue: "19001",
        min: 1,
        max: 65535,
        restart: true,
      },
      {
        key: "HOME_MINIO_PUBLIC_ENDPOINT",
        label: "MinIO 访问地址",
        help: "NewWaule 可访问的 MinIO 地址，通常填写 HomeServer 的 Tailscale IP 和 API 端口。",
        placeholder: "http://100.x.y.z:19000",
        wide: true,
      },
      {
        key: "HOME_MINIO_CONSOLE_PUBLIC_URL",
        label: "MinIO 控制台地址",
        help: "管理页面展示和跳转使用的 Console 地址。",
        placeholder: "http://192.168.100.2:19001",
        wide: true,
      },
    ],
  },
  {
    id: "newwaule",
    title: "NewWaule 连接",
    description: "管理 NewWaule 与 Home MinIO 之间的控制、缓存回推和 MinIO 访问凭据。",
    fields: [
      {
        key: "MINIO_INTERNAL_ENDPOINT",
        label: "MinIO 容器内地址",
        help: "Home MinIO 后端在 Docker 网络内写入 MinIO 的地址，通常不需要修改。",
        defaultValue: "http://minio:9000",
        restart: true,
      },
      {
        key: "MINIO_WAULE_ACCESS_KEY",
        label: "NewWaule Access Key",
        help: "提供给 NewWaule 使用的 MinIO 服务账号。",
        defaultValue: "waule-newwaule",
        restart: true,
      },
      {
        key: "MINIO_WAULE_SECRET_KEY",
        label: "NewWaule Secret Key",
        help: "上述 MinIO 服务账号的密码；留空表示保持现有值。",
        type: "password",
        restart: true,
      },
      {
        key: "NEWWAULE_API_BASE_URL",
        label: "NewWaule API 地址",
        help: "Home MinIO 回推冷文件缓存时访问的 NewWaule 公网 API 根地址。",
        placeholder: "https://api.waule.ai",
        wide: true,
      },
      {
        key: "NEWWAULE_CACHE_UPLOAD_BASE_URL",
        label: "缓存回推接口",
        help: "可留空，系统会根据 NewWaule API 地址自动生成缓存上传接口。",
        placeholder: "留空自动生成",
        wide: true,
      },
      {
        key: "NEWWAULE_HOME_MINIO_TOKEN",
        label: "旧版缓存回推令牌",
        help: "仅用于兼容旧配置；保存管理 API 令牌时会自动同步。",
        type: "password",
        hidden: true,
      },
      {
        key: "CACHE_PUSH_CONCURRENCY",
        label: "缓存回推并发",
        help: "冷文件回推到 NewWaule 的并行任务数；家庭上行稳定时可适当提高。",
        type: "number",
        defaultValue: "4",
        min: 1,
        max: 32,
      },
    ],
  },
  {
    id: "transfer",
    title: "媒体传输",
    description: "控制 NewWaule 拉取、OSS 上传和大文件分片并发。",
    fields: [
      {
        key: "HOME_MINIO_STATE_DB",
        label: "任务状态数据库",
        help: "保存传输任务、重试和 Multipart 断点的本机 SQLite 文件。",
        defaultValue: "/data/state/home-minio.sqlite",
        restart: true,
        wide: true,
      },
      {
        key: "HOME_MINIO_TRANSFER_WORK_DIR",
        label: "大文件临时目录",
        help: "Multipart 上传前暂存并校验大文件的持久化目录。",
        defaultValue: "/data/transfer-work",
        restart: true,
        wide: true,
      },
      {
        key: "MEDIA_PULL_MANIFEST_PATH",
        label: "兼容清单文件",
        help: "旧版手动归档流程使用的 NDJSON 清单位置；新生命周期通常无需修改。",
        defaultValue: "./backup/newwaule-media-manifest.jsonl",
        wide: true,
      },
      {
        key: "MEDIA_PULL_WORK_DIR",
        label: "拉取工作目录",
        help: "保存旧版清单拉取过程中的错误记录和临时状态。",
        defaultValue: "./backup/pull",
        wide: true,
      },
      {
        key: "MEDIA_PULL_CONCURRENCY",
        label: "NewWaule 拉取并发",
        help: "Home MinIO 同时从 NewWaule 公网地址拉取的文件数。",
        type: "number",
        defaultValue: "4",
        min: 1,
        max: 32,
        restart: true,
      },
      {
        key: "OSS_FILE_CONCURRENCY",
        label: "OSS 文件并发",
        help: "同时上传到 OSS 的文件数量。",
        type: "number",
        defaultValue: "8",
        min: 1,
        max: 64,
        restart: true,
      },
      {
        key: "OSS_MULTIPART_CONCURRENCY",
        label: "单文件分片并发",
        help: "一个大文件同时上传的 Multipart 分片数量。",
        type: "number",
        defaultValue: "4",
        min: 1,
        max: 16,
        restart: true,
      },
      {
        key: "OSS_MAX_HTTP_CONCURRENCY",
        label: "全局 HTTP 并发",
        help: "拉取、校验和 OSS 上传共享的网络请求总上限。",
        type: "number",
        defaultValue: "16",
        min: 2,
        max: 128,
        restart: true,
      },
      {
        key: "OSS_MULTIPART_THRESHOLD_BYTES",
        label: "Multipart 启用阈值",
        help: "文件达到该字节数后启用断点续传；默认 64 MiB。",
        type: "number",
        defaultValue: "67108864",
        min: 5242880,
        restart: true,
      },
      {
        key: "OSS_PART_SIZE_BYTES",
        label: "Multipart 分片大小",
        help: "每个 OSS 分片的字节数；默认 16 MiB。",
        type: "number",
        defaultValue: "16777216",
        min: 5242880,
        restart: true,
      },
    ],
  },
  {
    id: "backup",
    title: "备份与恢复",
    description: "配置 Home MinIO 到百度网盘的额外备份，可完全关闭。",
    fields: [
      {
        key: "BAIDUPAN_BACKUP_ENABLED",
        label: "启用百度网盘备份",
        help: "关闭后不执行定时百度网盘备份。",
        type: "select",
        defaultValue: "false",
        options: [["false", "关闭"], ["true", "开启"]],
      },
      {
        key: "BAIDUPAN_TOOL",
        label: "备份工具",
        help: "SVIP 推荐 BaiduPCS-Go；普通账号也可以使用 bypy。",
        type: "select",
        defaultValue: "baidupcs",
        options: [["baidupcs", "BaiduPCS-Go"], ["bypy", "bypy"]],
      },
      {
        key: "BAIDUPAN_REMOTE_DIR",
        label: "网盘目标目录",
        help: "备份文件在百度网盘中的保存目录。",
        defaultValue: "/NewWaule/home-minio",
        wide: true,
      },
      {
        key: "BAIDUPAN_WORK_DIR",
        label: "本地备份目录",
        help: "生成备份清单、日志和临时文件的宿主机目录。",
        defaultValue: "./backup",
        wide: true,
      },
      {
        key: "BAIDUPAN_CRON_SCHEDULE",
        label: "自动备份时间",
        help: "Cron 表达式；默认每天 03:35 执行。",
        defaultValue: "35 3 * * *",
      },
      {
        key: "BAIDUPCS_MAX_PARALLEL",
        label: "BaiduPCS-Go 并发",
        help: "BaiduPCS-Go 上传文件时使用的最大并发数。",
        type: "number",
        defaultValue: "16",
        min: 1,
        max: 64,
      },
      {
        key: "BAIDUPCS_UPLOAD_NORAPID",
        label: "跳过百度秒传",
        help: "避免部分账号缺少 STOKEN 时秒传接口失败，建议保持开启。",
        type: "select",
        defaultValue: "true",
        options: [["true", "开启"], ["false", "关闭"]],
      },
      {
        key: "BYPY_BIN",
        label: "bypy 命令",
        help: "容器内 bypy 可执行文件名称或路径，通常无需修改。",
        defaultValue: "bypy",
      },
      {
        key: "BAIDUPCS_BIN",
        label: "BaiduPCS-Go 命令",
        help: "容器内 BaiduPCS-Go 可执行文件名称或路径。",
        defaultValue: "BaiduPCS-Go",
      },
      {
        key: "BAIDUPCS_CONFIG_DIR",
        label: "BaiduPCS-Go 配置目录",
        help: "保存百度账号登录信息的持久化目录。",
        defaultValue: "/root/.config/BaiduPCS-Go",
        wide: true,
      },
    ],
  },
  {
    id: "advanced",
    title: "控制台设置",
    description: "管理 Home MinIO 控制台自身的端口和访问令牌。",
    fields: [
      {
        key: "HOME_MINIO_WEB_API_PORT",
        label: "管理 API 端口",
        help: "NewWaule 调用 Home MinIO 控制接口的宿主机端口。",
        type: "number",
        defaultValue: "19090",
        min: 1,
        max: 65535,
        restart: true,
      },
      {
        key: "HOME_MINIO_WEB_PORT",
        label: "管理页面端口",
        help: "浏览器打开当前控制台页面的宿主机端口。",
        type: "number",
        defaultValue: "19091",
        min: 1,
        max: 65535,
        restart: true,
      },
      {
        key: "HOME_MINIO_WEB_TOKEN",
        label: "管理 API 令牌",
        help: "同时用于控制台、生命周期 API 和缓存回推；必须与 NewWaule 后台保存的令牌一致，留空不修改。",
        type: "password",
        wide: true,
      },
    ],
  },
];

export const CONFIG_FIELDS = new Map(
  CONFIG_PAGES.flatMap((page) => page.fields.map((field) => [field.key, { ...field, pageId: page.id }])),
);

export const SECRET_CONFIG_KEYS = new Set(
  [...CONFIG_FIELDS.values()].filter((field) => field.type === "password").map((field) => field.key),
);
